# Generated by Django 4.0.6 on 2022-10-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='checked',
        ),
        migrations.AddField(
            model_name='products',
            name='problems',
            field=models.BooleanField(default=False),
        ),
    ]
