# Generated by Django 4.0.6 on 2022-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_products_color1_products_color2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color1',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color2',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
