# Generated by Django 4.0.6 on 2022-10-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_wanted_remove_cartitem_cart_remove_orders_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color1',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='products',
            name='color2',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='color1',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='color2',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
