# Generated by Django 4.0.6 on 2022-09-29 18:46

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=10)),
                ('checked', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=500, size=6)),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
