# Generated by Django 4.1.1 on 2022-10-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='/blessedimg.jpeg', upload_to='')),
                ('maxprice', models.FloatField(default=0)),
                ('color1', models.CharField(default='#FFFFFF', max_length=7)),
                ('color2', models.CharField(default='#000000', max_length=7)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='problems',
        ),
        migrations.AddField(
            model_name='products',
            name='color1',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='products',
            name='color2',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
