# Generated by Django 4.0.6 on 2022-10-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_cartitem_image_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
