# Generated by Django 4.0.6 on 2022-10-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_products_color1_alter_products_color2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='image',
            field=models.ImageField(default='/blessedimg.jpeg', upload_to=''),
        ),
    ]
