# Generated by Django 4.0.6 on 2022-10-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_wanted_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
