# Generated by Django 4.0.6 on 2022-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.CharField(default='Slovakia', max_length=20),
        ),
        migrations.AddField(
            model_name='wanted',
            name='country',
            field=models.CharField(default='Slovakia', max_length=20),
        ),
    ]
