# Generated by Django 4.0.6 on 2022-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_products_country_wanted_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='country',
            field=models.CharField(max_length=20),
        ),
    ]
