# Generated by Django 4.0.6 on 2022-11-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_products_options_alter_wanted_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='wanted',
            options={'verbose_name_plural': 'Wanted'},
        ),
    ]
